version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${USERNAME_MONGO}"
      MONGO_INITDB_ROOT_PASSWORD: "${USERPWD_MONGO}"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    container_name: mongoexpress
    image: mongo-express
    restart: always
    depends_on:
      - "mongodb"
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${USERNAME_MONGO}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${USERPWD_MONGO}"
      ME_CONFIG_MONGODB_URL: "mongodb://${USERNAME_MONGO}:${USERPWD_MONGO}@mongodb:27017?authSource=admin"
